apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
     providers:
      - aescbc:
          keys:
            - name: key1
              secret: X6An2L7deGL//+H/lQNnqR+ph4GR15fhOjLWbFWZIek=
      - identity: {} 
